fix: RRSet save comments
exonet/powerdns-php pull request #144
Opened 2023-10-17 19:33 UTC by bennetgallein

## Description

Hello, while testing i realized that the code-side of updating/adding comments is there, just missing in the transformers for the actual request. This PR adds the functionality and should work as expected.

Relevant docs: https://doc.powerdns.com/authoritative/http-api/zone.html#rrset

## Motivation and context

Well

## How has this been tested?

./run-test script runs through no problem, changing my local development env to my github repo and adding/updating comments updates them accordingly

Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.

## Screenshots (if appropriate)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](../.github/CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] My pull request contains a title that can be used as a release note.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

2023-10-18 09:21 UTC, trizz commented on tests/HelperTest.php
> +        self::assertSame('Hello World', $result->getComments()[0]->getContent());
```suggestion
        self::assertSame('Hello World', $result->getComments()[0]->getContent());
        self::assertSame('Tester', $result->getComments()[0]->getAccount());
```

2023-10-18 09:22 UTC, trizz commented on tests/HelperTest.php
> +        self::assertSame(111, $result->getComments()[1]->getModifiedAt());
```suggestion
        self::assertSame(111, $result->getComments()[1]->getModifiedAt());
        self::assertSame('World', $result->getComments()[1]->getContent());
        self::assertSame('rooti', $result->getComments()[1]->getAccount());
```

2023-10-18 09:27 UTC, trizz commented
Hi @bennetgallein 

Thanks for your PR! It's looking good, but I've made some small suggestions in your tests because you forgot to add some assertions. Also, please run [php-cs-fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) to [fix this files](https://github.com/exonet/powerdns-php/actions/runs/6552525914/job/17808895837?pr=144#step:4:6). Because this is a PR the required GitHub action can't commit to your fork.

2023-10-18 15:46 UTC, bennetgallein commented
Relevant files are updated :+1: My auto-formatter wants to format differently so no saving + formatting for me :)

2023-10-19 14:24 UTC, bennet-esyoil commented
ping ping @trizz :)

2023-10-23 11:59 UTC, robbinjanssen requested changes

2023-10-23 11:59 UTC, robbinjanssen commented on src/Zone.php
> +     * @param int            $ttl      The TTL.
```suggestion
     * @param int            $ttl      The TTL.
     * @param array|mixed[]  $comments The comment to assign to the record.
```

2023-10-23 12:02 UTC, robbinjanssen commented
@bennetgallein i've created a discussion for your suggestion about the syntax, can you maybe provide a bit of pseudo code there of what you want to achieve? :)

2023-10-23 12:03 UTC, bennetgallein commented on src/Zone.php
> +     * @param int            $ttl      The TTL.
Pushed!~

2023-10-23 12:20 UTC, merged

2023-10-23 12:22 UTC, robbinjanssen commented
Published as v4.5.0! 👍🏻 Thanks!