new setSoaEdit and setSoaEditApi methods in Zone class
exonet/powerdns-php pull request #98
Opened 2022-03-11 01:18 UTC by mvdgeijn

## Description

Added the setSoaEdit and setSoaEditApi methods to the Zone class to be able to set the soa_edit and soa_edit_api domain metadata.

## Motivation and context

Doesn't fix an open issue, just adding an extra feature

## How has this been tested?

New methods tested on a live PowerDNS server v4.6

## Screenshots (if appropriate)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](../.github/CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] My pull request contains a title that can be used as a release note.
- [x] I have added the appropriate labels to my pull request (e.g. breaking-change, new-feature, bugfix).
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

2022-03-11 01:34 UTC, mvdgeijn commented
How can I add a label to this PR? The label should be 'new-feature'

2022-03-14 08:29 UTC, robbinjanssen requested changes
Added a few dots at the end of lines :-)

2022-03-14 08:29 UTC, robbinjanssen commented on src/Zone.php
> +    }
```suggestion
    /**
     * Set a new value for the SOA_EDIT setting for this zone.
     *
     * @param string $value New value for the soa_edit meta setting.
     *
     * @return bool True when the request succeeded.
     */
    public function setSoaEdit(string $value): bool
    {
        return $this->put(new SoaEditTransformer(['soa_edit' => $value]));
    }

    /**
     * Set a new value for the SOA_EDIT_API setting for this zone.
     *
     * @param string $value New value for the soa_edit_api meta setting.
     *
     * @return bool True when the request succeeded.
     */
    public function setSoaEditApi(string $value): bool
    {
        return $this->put(new SoaEditApiTransformer(['soa_edit_api' => $value]));
    }
```

2022-03-14 11:23 UTC, merged

2022-03-14 12:29 UTC, robbinjanssen commented
@mvdgeijn tagged as [v4.1.0](https://github.com/exonet/powerdns-php/releases/tag/v4.1.0). Thanks for your contribution!